from selenium.webdriver.common.by import By

class AuthLocators:
    PRODUCT_TITLE = (By.CLASS_NAME, 'what-is__title')
    FORM_TITLE = (By.CLASS_NAME, 'card-container__title')
    INPUT_TITLE = (By.CLASS_NAME, 'rt-input__placeholder')
    REGISTRATION_LINK = (By.ID, 'kc-register')
    USERNAME = (By.ID, 'username')
    PASSWORD = (By.ID, 'password')
    BTN_LOGIN = (By.ID, 'kc-login')
    VK_LINK = (By.ID, 'oidc_vk')
    OK_LINK = (By.ID, 'oidc_ok')
    MAIL_RU_LINK = (By.ID, 'oidc_mail')
    YA_LINK = (By.ID, 'oidc_ya')
    FORGOT_PASSWORD_LINK = (By.ID, 'forgot_password')
    LK_NAV_BAR = (By.ID, 'lk-btn')
    ERROR_INVALID_DATA = (By.XPATH, '//*[@id="form-error-message"]')
    TAB_EMAIL = (By.ID, 't-btn-tab-mail')
    TAB_LOGIN = (By.ID, 't-btn-tab-login')
    TAB_LS = (By.ID, 't-btn-tab-ls')
    ERROR_MESSAGE = (By.CSS_SELECTOR, ".rt-input-container__meta--error")
    AGREEMENT = (By.LINK_TEXT, 'пользовательского соглашения')
    OFFER_TITLE = (By.CLASS_NAME, 'offer-title')
    TAB_PHONE = (By.ID, 't-btn-tab-phone')